[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.lifecycle]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 